class User {
  String? userID,
      fname,
      mname,
      lname,
      email,
      phone,
      country,
      status,
      customerType,
      hasCustodian,
      custodianApproved,
      dseAccount,
      bankID,
      banckAcNo,
      bankAcName,
      bankBranch,
      subscription,
      riskStatus,
      profileImg;

  User(
      {required this.banckAcNo,
      required this.bankAcName,
      required this.bankBranch,
      required this.bankID,
      required this.country,
      required this.custodianApproved,
      required this.customerType,
      required this.dseAccount,
      required this.email,
      required this.fname,
      required this.hasCustodian,
      required this.lname,
      required this.mname,
      required this.phone,
      required this.profileImg,
      required this.riskStatus,
      required this.status,
      required this.subscription,
      required this.userID});
}
