// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvbFJetM9Woc_6NJfnT2gxHIJ_7QDaKdY',
    appId: '1:899276707559:web:11a0bbdfdb0c7763f2f442',
    messagingSenderId: '899276707559',
    projectId: 'iwealth-48ef6',
    authDomain: 'iwealth-48ef6.firebaseapp.com',
    storageBucket: 'iwealth-48ef6.appspot.com',
    measurementId: 'G-K1B3Y7PTW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB11LQvLRqkE6cLLTTEsiACNDqM-k-ZWy8',
    appId: '1:899276707559:android:b1077d5f6bd9680af2f442',
    messagingSenderId: '899276707559',
    projectId: 'iwealth-48ef6',
    storageBucket: 'iwealth-48ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgvOgcJ0tN5dPuF8FHz7iFEcNAt_iH6Q',
    appId: '1:899276707559:ios:e13ca71514b5c8d3f2f442',
    messagingSenderId: '899276707559',
    projectId: 'iwealth-48ef6',
    storageBucket: 'iwealth-48ef6.appspot.com',
    iosBundleId: 'tz.co.itrust.iwealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgvOgcJ0tN5dPuF8FHz7iFEcNAt_iH6Q',
    appId: '1:899276707559:ios:e13ca71514b5c8d3f2f442',
    messagingSenderId: '899276707559',
    projectId: 'iwealth-48ef6',
    storageBucket: 'iwealth-48ef6.appspot.com',
    iosBundleId: 'tz.co.itrust.iwealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvbFJetM9Woc_6NJfnT2gxHIJ_7QDaKdY',
    appId: '1:899276707559:web:1ed131d24f23f698f2f442',
    messagingSenderId: '899276707559',
    projectId: 'iwealth-48ef6',
    authDomain: 'iwealth-48ef6.firebaseapp.com',
    storageBucket: 'iwealth-48ef6.appspot.com',
    measurementId: 'G-6L3LC1PN40',
  );

}