// class KYC
import 'dart:io';

class USERKYC {
  File?
      // tinDoc,
      passportSizeDoc,
      signatureDoc;
  String? investorPhone,
      dseAccount,
      region,
      district,
      ward,
      placeOfBirth,
      fname,
      mname,
      lname,
      title,
      dob,
      gender,
      nida,
      tinNumber,
      address,
      nationality,
      country,
      banckAcNo,
      bankAcName,
      bank,
      bankBranch,
      employmentStatus,
      employerName,
      other,
      businessSector,
      occupation,
      sourceOfIncome,
      incomeFreq,
  nextKinName,
  nextKinMobile,
  kinEmail,
  kinRelationship;

  USERKYC({
    required this.address,
    this.businessSector,
    required this.country,
    required this.dob,
    this.employerName,
    this.employmentStatus,
    required this.fname,
    required this.gender,
    required this.investorPhone,
    required this.lname,
    required this.mname,
    required this.nationality,
    this.kinEmail,
    this.nextKinMobile,
    this.nextKinName,
    required this.nida,
    this.occupation,
    required this.signatureDoc,
    this.tinNumber,
    required this.title,
    this.banckAcNo, 
    this.bank,
    this.bankAcName,
    this.bankBranch, 
    this.district,
    this.dseAccount,
    this.incomeFreq,
    required this.placeOfBirth,
    this.region,
    this.sourceOfIncome,
    this.ward,
    this.kinRelationship,
  });
}
